name: Run Unit Tests

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    - name: Install dependencies
      run: |
        chmod +x gradlew
        ./gradlew build

    - name: Run tests
      run: ./gradlew test
